In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#importing csv
wego = pd.read_csv(r"C:\Users\ekims\Documents\NSS\DA14\Projects\wego-partnerproject-da14-v2-ekimshaf\data\wego_tsp_assigned.csv")

In [3]:
wego.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 337365 entries, 0 to 337364
Data columns (total 37 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   CALENDAR_ID                337365 non-null  int64
 1   SERVICE_ABBR               337365 non-null  int64
 2   ADHERENCE_ID               337365 non-null  int64
 3   DATE                       337365 non-null  object
 4   ROUTE_ABBR                 337365 non-null  int64
 5   BLOCK_ABBR                 337365 non-null  int64
 6   OPERATOR                   337365 non-null  int64
 7   TRIP_ID                    337365 non-null  int64
 8   OVERLOAD_ID                337365 non-null  int64
 9   ROUTE_DIRECTION_NAME       337365 non-null  object
 10  TIME_POINT_ABBR            337365 non-null  object
 11  ROUTE_STOP_SEQUENCE        337365 non-null  int64
 12  TRIP_EDGE                  337365 non-null  int64
 13  LATITUDE                   337365 non-null  float64
 14  LONGITUDE                  337365 non-null  float64
 15  SCHEDULED_TIME             337365 non-null  object
 16  ACTUAL_ARRIVAL_TIME        337364 non-null  object
 17  ACTUAL_DEPARTURE_TIME      337365 non-null  object
 18  ADHERENCE                  337365 non-null  float64
 19  SCHEDULED_HDWY             337365 non-null  float64
 20  ACTUAL_HDWY                337365 non-null  float64
 21  HDWY_DEV                   337365 non-null  float64
 22  ADJUSTED_EARLY_COUNT       337365 non-null  int64
 23  ADJUSTED_LATE_COUNT        337365 non-null  int64
 24  ADJUSTED_ONTIME_COUNT      337365 non-null  int64
 25  STOP_CANCELLED             337365 non-null  int64
 26  PREV_SCHED_STOP_CANCELLED  337365 non-null  float64
 27  IS_RELIEF                  337365 non-null  int64
 28  BLOCK_STOP_ORDER           337365 non-null  int64
 29  DWELL_IN_MINS              337365 non-null  float64
 30  TIME_OF_DAY                337365 non-null  object
 31  SEASON                     337365 non-null  object
 32  IS_HOLIDAY                 337365 non-null  bool
 33  IN_SCHOOL_ZONE_TIME        337365 non-null  object
 34  DAY_TYPE                   337365 non-null  object
 35  TSP_PHASE_NAME             337365 non-null  object
 36  TSP_ACTIVE                 323366 non-null  object
dtypes: bool(1), float64(8), int64(16), object(12)
memory usage: 93.0+ MB

In [4]:
wego.head()

,CALENDAR_ID,SERVICE_ABBR,ADHERENCE_ID,DATE,ROUTE_ABBR,BLOCK_ABBR,OPERATOR,TRIP_ID,OVERLOAD_ID,ROUTE_DIRECTION_NAME,...,IS_RELIEF,BLOCK_STOP_ORDER,DWELL_IN_MINS,TIME_OF_DAY,SEASON,IS_HOLIDAY,IN_SCHOOL_ZONE_TIME,DAY_TYPE,TSP_PHASE_NAME,TSP_ACTIVE
0,120230101,3,93549175,2023-01-01,50,5000,2355,332424,0,TO DOWNTOWN,...,0,59,1.683333,AM Peak,Winter,False,N,Sunday,Pre-TSP,N
1,120230101,3,93549176,2023-01-01,50,5000,2355,332424,0,TO DOWNTOWN,...,0,61,0.000000,AM Peak,Winter,False,N,Sunday,Pre-TSP,N
2,120230101,3,93549177,2023-01-01,50,5000,2355,332424,0,TO DOWNTOWN,...,0,66,0.000000,AM Peak,Winter,False,N,Sunday,Pre-TSP,N
3,120230101,3,93549179,2023-01-01,50,5000,2355,332425,0,FROM DOWNTOWN,...,0,74,17.850000,AM Peak,Winter,False,N,Sunday,Pre-TSP,N
4,120230101,3,93549180,2023-01-01,50,5000,2355,332425,0,FROM DOWNTOWN,...,0,81,0.000000,AM Peak,Winter,False,N,Sunday,Pre-TSP,N

1) This section begins parsing out the time and date points of TSP activation in the data into 
individual dataframes.

In [28]:
#Sectioning out data from before TSP activation in dataset for route in question.
# TSP began on 2/3/2025 at 12:00pm (noon)
before_tsp = wego[(wego['CALENDAR_ID'] <= 120250203) & 
(wego['TSP_PHASE_NAME'].str.contains('Pre-TSP'))]
before_tsp.info()

<class 'pandas.core.frame.DataFrame'>
Index: 298732 entries, 0 to 298946
Data columns (total 37 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   CALENDAR_ID                298732 non-null  int64
 1   SERVICE_ABBR               298732 non-null  int64
 2   ADHERENCE_ID               298732 non-null  int64
 3   DATE                       298732 non-null  object
 4   ROUTE_ABBR                 298732 non-null  int64
 5   BLOCK_ABBR                 298732 non-null  int64
 6   OPERATOR                   298732 non-null  int64
 7   TRIP_ID                    298732 non-null  int64
 8   OVERLOAD_ID                298732 non-null  int64
 9   ROUTE_DIRECTION_NAME       298732 non-null  object
 10  TIME_POINT_ABBR            298732 non-null  object
 11  ROUTE_STOP_SEQUENCE        298732 non-null  int64
 12  TRIP_EDGE                  298732 non-null  int64
 13  LATITUDE                   298732 non-null  float64
 14  LONGITUDE                  298732 non-null  float64
 15  SCHEDULED_TIME             298732 non-null  object
 16  ACTUAL_ARRIVAL_TIME        298731 non-null  object
 17  ACTUAL_DEPARTURE_TIME      298732 non-null  object
 18  ADHERENCE                  298732 non-null  float64
 19  SCHEDULED_HDWY             298732 non-null  float64
 20  ACTUAL_HDWY                298732 non-null  float64
 21  HDWY_DEV                   298732 non-null  float64
 22  ADJUSTED_EARLY_COUNT       298732 non-null  int64
 23  ADJUSTED_LATE_COUNT        298732 non-null  int64
 24  ADJUSTED_ONTIME_COUNT      298732 non-null  int64
 25  STOP_CANCELLED             298732 non-null  int64
 26  PREV_SCHED_STOP_CANCELLED  298732 non-null  float64
 27  IS_RELIEF                  298732 non-null  int64
 28  BLOCK_STOP_ORDER           298732 non-null  int64
 29  DWELL_IN_MINS              298732 non-null  float64
 30  TIME_OF_DAY                298732 non-null  object
 31  SEASON                     298732 non-null  object
 32  IS_HOLIDAY                 298732 non-null  bool
 33  IN_SCHOOL_ZONE_TIME        298732 non-null  object
 34  DAY_TYPE                   298732 non-null  object
 35  TSP_PHASE_NAME             298732 non-null  object
 36  TSP_ACTIVE                 298732 non-null  object
dtypes: bool(1), float64(8), int64(16), object(12)
memory usage: 84.6+ MB

In [32]:
before_tsp

,CALENDAR_ID,SERVICE_ABBR,ADHERENCE_ID,DATE,ROUTE_ABBR,BLOCK_ABBR,OPERATOR,TRIP_ID,OVERLOAD_ID,ROUTE_DIRECTION_NAME,...,IS_RELIEF,BLOCK_STOP_ORDER,DWELL_IN_MINS,TIME_OF_DAY,SEASON,IS_HOLIDAY,IN_SCHOOL_ZONE_TIME,DAY_TYPE,TSP_PHASE_NAME,TSP_ACTIVE
0,120230101,3,93549175,2023-01-01,50,5000,2355,332424,0,TO DOWNTOWN,...,0,59,1.683333,AM Peak,Winter,False,N,Sunday,Pre-TSP,N
1,120230101,3,93549176,2023-01-01,50,5000,2355,332424,0,TO DOWNTOWN,...,0,61,0.000000,AM Peak,Winter,False,N,Sunday,Pre-TSP,N
2,120230101,3,93549177,2023-01-01,50,5000,2355,332424,0,TO DOWNTOWN,...,0,66,0.000000,AM Peak,Winter,False,N,Sunday,Pre-TSP,N
3,120230101,3,93549179,2023-01-01,50,5000,2355,332425,0,FROM DOWNTOWN,...,0,74,17.850000,AM Peak,Winter,False,N,Sunday,Pre-TSP,N
4,120230101,3,93549180,2023-01-01,50,5000,2355,332425,0,FROM DOWNTOWN,...,0,81,0.000000,AM Peak,Winter,False,N,Sunday,Pre-TSP,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298942,120250203,1,117340535,2025-02-03,50,5005,2548,418024,0,FROM DOWNTOWN,...,0,139,0.000000,Midday,Winter,False,N,Weekday,Pre-TSP,N
298943,120250203,1,117340536,2025-02-03,50,5005,2548,418024,0,FROM DOWNTOWN,...,0,142,0.000000,Midday,Winter,False,N,Weekday,Pre-TSP,N
298944,120250203,1,117340541,2025-02-03,50,5005,2548,418025,0,TO DOWNTOWN,...,0,161,1.766666,Midday,Winter,False,N,Weekday,Pre-TSP,N
298945,120250203,1,117340542,2025-02-03,50,5005,2548,418025,0,TO DOWNTOWN,...,0,164,0.000000,Midday,Winter,False,N,Weekday,Pre-TSP,N
298946,120250203,1,117340543,2025-02-03,50,5005,2548,418025,0,TO DOWNTOWN,...,0,169,0.000000,Midday,Winter,False,N,Weekday,Pre-TSP,N

In [30]:
##filtering dates that are included in unconditional TSP, Feb 3rd - Feb 10th, 2025 11:59am
tsp_uncon_feb = wego[(wego['CALENDAR_ID'] >= 120250203) & 
(wego['CALENDAR_ID'] <= 120250210) &
(wego['TSP_PHASE_NAME'].str.contains('TSP Unconditional 1'))]
tsp_uncon_feb.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2830 entries, 298541 to 301758
Data columns (total 37 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   CALENDAR_ID                2830 non-null   int64
 1   SERVICE_ABBR               2830 non-null   int64
 2   ADHERENCE_ID               2830 non-null   int64
 3   DATE                       2830 non-null   object
 4   ROUTE_ABBR                 2830 non-null   int64
 5   BLOCK_ABBR                 2830 non-null   int64
 6   OPERATOR                   2830 non-null   int64
 7   TRIP_ID                    2830 non-null   int64
 8   OVERLOAD_ID                2830 non-null   int64
 9   ROUTE_DIRECTION_NAME       2830 non-null   object
 10  TIME_POINT_ABBR            2830 non-null   object
 11  ROUTE_STOP_SEQUENCE        2830 non-null   int64
 12  TRIP_EDGE                  2830 non-null   int64
 13  LATITUDE                   2830 non-null   float64
 14  LONGITUDE                  2830 non-null   float64
 15  SCHEDULED_TIME             2830 non-null   object
 16  ACTUAL_ARRIVAL_TIME        2830 non-null   object
 17  ACTUAL_DEPARTURE_TIME      2830 non-null   object
 18  ADHERENCE                  2830 non-null   float64
 19  SCHEDULED_HDWY             2830 non-null   float64
 20  ACTUAL_HDWY                2830 non-null   float64
 21  HDWY_DEV                   2830 non-null   float64
 22  ADJUSTED_EARLY_COUNT       2830 non-null   int64
 23  ADJUSTED_LATE_COUNT        2830 non-null   int64
 24  ADJUSTED_ONTIME_COUNT      2830 non-null   int64
 25  STOP_CANCELLED             2830 non-null   int64
 26  PREV_SCHED_STOP_CANCELLED  2830 non-null   float64
 27  IS_RELIEF                  2830 non-null   int64
 28  BLOCK_STOP_ORDER           2830 non-null   int64
 29  DWELL_IN_MINS              2830 non-null   float64
 30  TIME_OF_DAY                2830 non-null   object
 31  SEASON                     2830 non-null   object
 32  IS_HOLIDAY                 2830 non-null   bool
 33  IN_SCHOOL_ZONE_TIME        2830 non-null   object
 34  DAY_TYPE                   2830 non-null   object
 35  TSP_PHASE_NAME             2830 non-null   object
 36  TSP_ACTIVE                 2830 non-null   object
dtypes: bool(1), float64(8), int64(16), object(12)
memory usage: 820.8+ KB

In [34]:
tsp_uncon_feb

,CALENDAR_ID,SERVICE_ABBR,ADHERENCE_ID,DATE,ROUTE_ABBR,BLOCK_ABBR,OPERATOR,TRIP_ID,OVERLOAD_ID,ROUTE_DIRECTION_NAME,...,IS_RELIEF,BLOCK_STOP_ORDER,DWELL_IN_MINS,TIME_OF_DAY,SEASON,IS_HOLIDAY,IN_SCHOOL_ZONE_TIME,DAY_TYPE,TSP_PHASE_NAME,TSP_ACTIVE
298541,120250203,1,117339007,2025-02-03,50,318,3443,417223,0,TO DOWNTOWN,...,0,2,35.766666,PM Peak,Winter,False,Y,Weekday,TSP Unconditional 1,N
298570,120250203,1,117339883,2025-02-03,50,5000,329,417735,0,TO DOWNTOWN,...,0,261,2.366666,Midday,Winter,False,N,Weekday,TSP Unconditional 1,Y
298571,120250203,1,117339884,2025-02-03,50,5000,329,417735,0,TO DOWNTOWN,...,0,264,0.000000,Midday,Winter,False,N,Weekday,TSP Unconditional 1,Y
298572,120250203,1,117339885,2025-02-03,50,5000,329,417735,0,TO DOWNTOWN,...,0,269,0.000000,Midday,Winter,False,N,Weekday,TSP Unconditional 1,Y
298573,120250203,1,117339887,2025-02-03,50,5000,329,417736,0,FROM DOWNTOWN,...,0,277,12.083333,Midday,Winter,False,N,Weekday,TSP Unconditional 1,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301754,120250210,1,117582258,2025-02-10,50,5005,2548,418024,0,FROM DOWNTOWN,...,0,139,0.000000,Midday,Winter,False,N,Weekday,TSP Unconditional 1,Y
301755,120250210,1,117582259,2025-02-10,50,5005,2548,418024,0,FROM DOWNTOWN,...,0,142,0.000000,Midday,Winter,False,N,Weekday,TSP Unconditional 1,Y
301756,120250210,1,117582264,2025-02-10,50,5005,2548,418025,0,TO DOWNTOWN,...,0,161,2.100000,Midday,Winter,False,N,Weekday,TSP Unconditional 1,Y
301757,120250210,1,117582265,2025-02-10,50,5005,2548,418025,0,TO DOWNTOWN,...,0,164,0.000000,Midday,Winter,False,N,Weekday,TSP Unconditional 1,Y
301758,120250210,1,117582266,2025-02-10,50,5005,2548,418025,0,TO DOWNTOWN,...,0,169,0.000000,Midday,Winter,False,N,Weekday,TSP Unconditional 1,Y

In [8]:
##filtering dates that are included in conditional TSP, Feb 10th - Apr 28, 2025
tsp_cond_feb = wego[(wego['CALENDAR_ID'] >= 120250210) & 
(wego['CALENDAR_ID'] <= 120250428) &
(wego['TSP_PHASE_NAME'].str.contains('TSP Schedule-Conditional'))]
tsp_cond_feb.info()

<class 'pandas.core.frame.DataFrame'>
Index: 29800 entries, 301399 to 331579
Data columns (total 37 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   CALENDAR_ID                29800 non-null  int64
 1   SERVICE_ABBR               29800 non-null  int64
 2   ADHERENCE_ID               29800 non-null  int64
 3   DATE                       29800 non-null  object
 4   ROUTE_ABBR                 29800 non-null  int64
 5   BLOCK_ABBR                 29800 non-null  int64
 6   OPERATOR                   29800 non-null  int64
 7   TRIP_ID                    29800 non-null  int64
 8   OVERLOAD_ID                29800 non-null  int64
 9   ROUTE_DIRECTION_NAME       29800 non-null  object
 10  TIME_POINT_ABBR            29800 non-null  object
 11  ROUTE_STOP_SEQUENCE        29800 non-null  int64
 12  TRIP_EDGE                  29800 non-null  int64
 13  LATITUDE                   29800 non-null  float64
 14  LONGITUDE                  29800 non-null  float64
 15  SCHEDULED_TIME             29800 non-null  object
 16  ACTUAL_ARRIVAL_TIME        29800 non-null  object
 17  ACTUAL_DEPARTURE_TIME      29800 non-null  object
 18  ADHERENCE                  29800 non-null  float64
 19  SCHEDULED_HDWY             29800 non-null  float64
 20  ACTUAL_HDWY                29800 non-null  float64
 21  HDWY_DEV                   29800 non-null  float64
 22  ADJUSTED_EARLY_COUNT       29800 non-null  int64
 23  ADJUSTED_LATE_COUNT        29800 non-null  int64
 24  ADJUSTED_ONTIME_COUNT      29800 non-null  int64
 25  STOP_CANCELLED             29800 non-null  int64
 26  PREV_SCHED_STOP_CANCELLED  29800 non-null  float64
 27  IS_RELIEF                  29800 non-null  int64
 28  BLOCK_STOP_ORDER           29800 non-null  int64
 29  DWELL_IN_MINS              29800 non-null  float64
 30  TIME_OF_DAY                29800 non-null  object
 31  SEASON                     29800 non-null  object
 32  IS_HOLIDAY                 29800 non-null  bool
 33  IN_SCHOOL_ZONE_TIME        29800 non-null  object
 34  DAY_TYPE                   29800 non-null  object
 35  TSP_PHASE_NAME             29800 non-null  object
 36  TSP_ACTIVE                 15981 non-null  object
dtypes: bool(1), float64(8), int64(16), object(12)
memory usage: 8.4+ MB

In [9]:
tsp_cond_feb

,CALENDAR_ID,SERVICE_ABBR,ADHERENCE_ID,DATE,ROUTE_ABBR,BLOCK_ABBR,OPERATOR,TRIP_ID,OVERLOAD_ID,ROUTE_DIRECTION_NAME,...,IS_RELIEF,BLOCK_STOP_ORDER,DWELL_IN_MINS,TIME_OF_DAY,SEASON,IS_HOLIDAY,IN_SCHOOL_ZONE_TIME,DAY_TYPE,TSP_PHASE_NAME,TSP_ACTIVE
301399,120250210,1,117581594,2025-02-10,50,5000,1419,417735,0,TO DOWNTOWN,...,0,261,2.650000,Midday,Winter,False,N,Weekday,TSP Schedule-Conditional,NaN
301400,120250210,1,117581595,2025-02-10,50,5000,1419,417735,0,TO DOWNTOWN,...,0,264,0.000000,Midday,Winter,False,N,Weekday,TSP Schedule-Conditional,Y
301401,120250210,1,117581596,2025-02-10,50,5000,1419,417735,0,TO DOWNTOWN,...,0,269,0.000000,Midday,Winter,False,N,Weekday,TSP Schedule-Conditional,Y
301402,120250210,1,117581598,2025-02-10,50,5000,1419,417736,0,FROM DOWNTOWN,...,0,277,5.766666,Midday,Winter,False,N,Weekday,TSP Schedule-Conditional,NaN
301403,120250210,1,117581599,2025-02-10,50,5000,1419,417736,0,FROM DOWNTOWN,...,0,284,2.233333,Midday,Winter,False,N,Weekday,TSP Schedule-Conditional,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331575,120250428,1,119086565,2025-04-28,50,5005,2548,429683,0,FROM DOWNTOWN,...,0,144,0.000000,Midday,Spring,False,N,Weekday,TSP Schedule-Conditional,Y
331576,120250428,1,119086566,2025-04-28,50,5005,2548,429683,0,FROM DOWNTOWN,...,0,147,0.000000,Midday,Spring,False,N,Weekday,TSP Schedule-Conditional,Y
331577,120250428,1,119086571,2025-04-28,50,5005,2548,429684,0,TO DOWNTOWN,...,0,168,3.050000,Midday,Spring,False,N,Weekday,TSP Schedule-Conditional,Y
331578,120250428,1,119086572,2025-04-28,50,5005,2548,429684,0,TO DOWNTOWN,...,0,171,0.000000,Midday,Spring,False,N,Weekday,TSP Schedule-Conditional,Y
331579,120250428,1,119086573,2025-04-28,50,5005,2548,429684,0,TO DOWNTOWN,...,0,176,0.000000,Midday,Spring,False,N,Weekday,TSP Schedule-Conditional,Y

In [10]:
#filtering dates with TSP off between Apr 28th and May 5th
tsp_off_apr = wego[(wego['CALENDAR_ID'] >= 120250428) & 
(wego['CALENDAR_ID'] <= 120250505) &
(wego['TSP_PHASE_NAME'].str.contains('TSP Off'))]
tsp_off_apr.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2853 entries, 331199 to 334429
Data columns (total 37 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   CALENDAR_ID                2853 non-null   int64
 1   SERVICE_ABBR               2853 non-null   int64
 2   ADHERENCE_ID               2853 non-null   int64
 3   DATE                       2853 non-null   object
 4   ROUTE_ABBR                 2853 non-null   int64
 5   BLOCK_ABBR                 2853 non-null   int64
 6   OPERATOR                   2853 non-null   int64
 7   TRIP_ID                    2853 non-null   int64
 8   OVERLOAD_ID                2853 non-null   int64
 9   ROUTE_DIRECTION_NAME       2853 non-null   object
 10  TIME_POINT_ABBR            2853 non-null   object
 11  ROUTE_STOP_SEQUENCE        2853 non-null   int64
 12  TRIP_EDGE                  2853 non-null   int64
 13  LATITUDE                   2853 non-null   float64
 14  LONGITUDE                  2853 non-null   float64
 15  SCHEDULED_TIME             2853 non-null   object
 16  ACTUAL_ARRIVAL_TIME        2853 non-null   object
 17  ACTUAL_DEPARTURE_TIME      2853 non-null   object
 18  ADHERENCE                  2853 non-null   float64
 19  SCHEDULED_HDWY             2853 non-null   float64
 20  ACTUAL_HDWY                2853 non-null   float64
 21  HDWY_DEV                   2853 non-null   float64
 22  ADJUSTED_EARLY_COUNT       2853 non-null   int64
 23  ADJUSTED_LATE_COUNT        2853 non-null   int64
 24  ADJUSTED_ONTIME_COUNT      2853 non-null   int64
 25  STOP_CANCELLED             2853 non-null   int64
 26  PREV_SCHED_STOP_CANCELLED  2853 non-null   float64
 27  IS_RELIEF                  2853 non-null   int64
 28  BLOCK_STOP_ORDER           2853 non-null   int64
 29  DWELL_IN_MINS              2853 non-null   float64
 30  TIME_OF_DAY                2853 non-null   object
 31  SEASON                     2853 non-null   object
 32  IS_HOLIDAY                 2853 non-null   bool
 33  IN_SCHOOL_ZONE_TIME        2853 non-null   object
 34  DAY_TYPE                   2853 non-null   object
 35  TSP_PHASE_NAME             2853 non-null   object
 36  TSP_ACTIVE                 2853 non-null   object
dtypes: bool(1), float64(8), int64(16), object(12)
memory usage: 827.5+ KB

In [11]:
tsp_off_apr

,CALENDAR_ID,SERVICE_ABBR,ADHERENCE_ID,DATE,ROUTE_ABBR,BLOCK_ABBR,OPERATOR,TRIP_ID,OVERLOAD_ID,ROUTE_DIRECTION_NAME,...,IS_RELIEF,BLOCK_STOP_ORDER,DWELL_IN_MINS,TIME_OF_DAY,SEASON,IS_HOLIDAY,IN_SCHOOL_ZONE_TIME,DAY_TYPE,TSP_PHASE_NAME,TSP_ACTIVE
331199,120250428,1,119085913,2025-04-28,50,5000,329,429394,0,TO DOWNTOWN,...,0,272,0.000000,Midday,Spring,False,N,Weekday,TSP Off,N
331200,120250428,1,119085914,2025-04-28,50,5000,329,429394,0,TO DOWNTOWN,...,0,275,0.000000,Midday,Spring,False,N,Weekday,TSP Off,N
331201,120250428,1,119085915,2025-04-28,50,5000,329,429394,0,TO DOWNTOWN,...,0,280,1.700000,Midday,Spring,False,N,Weekday,TSP Off,N
331202,120250428,1,119085917,2025-04-28,50,5000,329,429395,0,FROM DOWNTOWN,...,0,288,11.066666,Midday,Spring,False,N,Weekday,TSP Off,N
331203,120250428,1,119085918,2025-04-28,50,5000,329,429395,0,FROM DOWNTOWN,...,0,295,0.000000,Midday,Spring,False,N,Weekday,TSP Off,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
334425,120250505,1,119328666,2025-05-05,50,5005,3328,429683,0,FROM DOWNTOWN,...,0,144,0.000000,Midday,Spring,False,N,Weekday,TSP Off,N
334426,120250505,1,119328667,2025-05-05,50,5005,3328,429683,0,FROM DOWNTOWN,...,0,147,0.000000,Midday,Spring,False,N,Weekday,TSP Off,N
334427,120250505,1,119328672,2025-05-05,50,5005,3328,429684,0,TO DOWNTOWN,...,0,168,2.633333,Midday,Spring,False,N,Weekday,TSP Off,N
334428,120250505,1,119328673,2025-05-05,50,5005,3328,429684,0,TO DOWNTOWN,...,0,171,0.000000,Midday,Spring,False,N,Weekday,TSP Off,N
334429,120250505,1,119328674,2025-05-05,50,5005,3328,429684,0,TO DOWNTOWN,...,0,176,0.000000,Midday,Spring,False,N,Weekday,TSP Off,N

In [12]:
#Filtering dates for headway priority condition for TSP beginning May 12th
tsp_cond_may = wego[(wego['CALENDAR_ID'] >= 120250512) &
(wego['TSP_PHASE_NAME'].str.contains('TSP Headway-Conditional'))]
tsp_cond_may.info()

<class 'pandas.core.frame.DataFrame'>
Index: 266 entries, 336911 to 337364
Data columns (total 37 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   CALENDAR_ID                266 non-null    int64
 1   SERVICE_ABBR               266 non-null    int64
 2   ADHERENCE_ID               266 non-null    int64
 3   DATE                       266 non-null    object
 4   ROUTE_ABBR                 266 non-null    int64
 5   BLOCK_ABBR                 266 non-null    int64
 6   OPERATOR                   266 non-null    int64
 7   TRIP_ID                    266 non-null    int64
 8   OVERLOAD_ID                266 non-null    int64
 9   ROUTE_DIRECTION_NAME       266 non-null    object
 10  TIME_POINT_ABBR            266 non-null    object
 11  ROUTE_STOP_SEQUENCE        266 non-null    int64
 12  TRIP_EDGE                  266 non-null    int64
 13  LATITUDE                   266 non-null    float64
 14  LONGITUDE                  266 non-null    float64
 15  SCHEDULED_TIME             266 non-null    object
 16  ACTUAL_ARRIVAL_TIME        266 non-null    object
 17  ACTUAL_DEPARTURE_TIME      266 non-null    object
 18  ADHERENCE                  266 non-null    float64
 19  SCHEDULED_HDWY             266 non-null    float64
 20  ACTUAL_HDWY                266 non-null    float64
 21  HDWY_DEV                   266 non-null    float64
 22  ADJUSTED_EARLY_COUNT       266 non-null    int64
 23  ADJUSTED_LATE_COUNT        266 non-null    int64
 24  ADJUSTED_ONTIME_COUNT      266 non-null    int64
 25  STOP_CANCELLED             266 non-null    int64
 26  PREV_SCHED_STOP_CANCELLED  266 non-null    float64
 27  IS_RELIEF                  266 non-null    int64
 28  BLOCK_STOP_ORDER           266 non-null    int64
 29  DWELL_IN_MINS              266 non-null    float64
 30  TIME_OF_DAY                266 non-null    object
 31  SEASON                     266 non-null    object
 32  IS_HOLIDAY                 266 non-null    bool
 33  IN_SCHOOL_ZONE_TIME        266 non-null    object
 34  DAY_TYPE                   266 non-null    object
 35  TSP_PHASE_NAME             266 non-null    object
 36  TSP_ACTIVE                 86 non-null     object
dtypes: bool(1), float64(8), int64(16), object(12)
memory usage: 77.2+ KB

In [36]:
tsp_cond_may

,CALENDAR_ID,SERVICE_ABBR,ADHERENCE_ID,DATE,ROUTE_ABBR,BLOCK_ABBR,OPERATOR,TRIP_ID,OVERLOAD_ID,ROUTE_DIRECTION_NAME,...,IS_RELIEF,BLOCK_STOP_ORDER,DWELL_IN_MINS,TIME_OF_DAY,SEASON,IS_HOLIDAY,IN_SCHOOL_ZONE_TIME,DAY_TYPE,TSP_PHASE_NAME,TSP_ACTIVE
336911,120250512,1,119523125,2025-05-12,50,318,3443,428880,0,TO DOWNTOWN,...,0,2,27.800000,PM Peak,Spring,False,Y,Weekday,TSP Headway-Conditional,N
336940,120250512,1,119524028,2025-05-12,50,5000,1782,429394,0,TO DOWNTOWN,...,0,272,0.000000,Midday,Spring,False,N,Weekday,TSP Headway-Conditional,Y
336941,120250512,1,119524029,2025-05-12,50,5000,1782,429394,0,TO DOWNTOWN,...,0,275,0.000000,Midday,Spring,False,N,Weekday,TSP Headway-Conditional,Y
336942,120250512,1,119524030,2025-05-12,50,5000,1782,429394,0,TO DOWNTOWN,...,0,280,0.000000,Midday,Spring,False,N,Weekday,TSP Headway-Conditional,Y
336943,120250512,1,119524032,2025-05-12,50,5000,1782,429395,0,FROM DOWNTOWN,...,0,288,11.066666,Midday,Spring,False,N,Weekday,TSP Headway-Conditional,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
337360,120250512,1,119524764,2025-05-12,50,5006,754,429697,0,FROM DOWNTOWN,...,0,80,10.566666,PM Peak,Spring,False,N,Weekday,TSP Headway-Conditional,NaN
337361,120250512,1,119524765,2025-05-12,50,5006,754,429697,0,FROM DOWNTOWN,...,0,87,0.000000,PM Peak,Spring,False,N,Weekday,TSP Headway-Conditional,NaN
337362,120250512,1,119524766,2025-05-12,50,5006,754,429697,0,FROM DOWNTOWN,...,0,92,0.000000,PM Peak,Spring,False,N,Weekday,TSP Headway-Conditional,NaN
337363,120250512,1,119524767,2025-05-12,50,5006,754,429697,0,FROM DOWNTOWN,...,0,95,0.000000,PM Peak,Spring,False,N,Weekday,TSP Headway-Conditional,NaN
337364,120250512,1,119531770,2025-05-12,50,9950,2448,432387,0,TO DOWNTOWN,...,0,2,8.166666,PM Peak,Spring,False,Y,Weekday,TSP Headway-Conditional,N

2. Data has been sectioned out into dataframes for each timepoint:

Dataframe names:

before_tsp  
tsp_uncon_feb  
tsp_cond_feb  
tsp_off_apr  
tsp_cond_may